/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.cvut.fit.pivo.swing;

import cz.cvut.fit.pivo.controller.Controller;
import cz.cvut.fit.pivo.entities.Recipe;
import cz.cvut.fit.pivo.model.IModel;
import cz.cvut.fit.pivo.view.AbstractView;

/**
 *
 * @author Adam
 */
public class RecipeView extends AbstractView {

    /**
     * Creates new form RecipeView
     */
    public RecipeView(Controller controller, IModel model) {
        super(controller, model);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        vystirkaSlider = new javax.swing.JSlider();
        vystiraciCombo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        peptonizacniCombo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        nizsiCukrCombo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        vyssiCukrCombo = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        odrmutovaciCombo = new javax.swing.JComboBox();
        peptonizacniSlider = new javax.swing.JSlider();
        vyssiCukrotvornaSlider = new javax.swing.JSlider();
        odrmutovaciSlider = new javax.swing.JSlider();
        nizsiCukrotvornaSlider = new javax.swing.JSlider();
        vystrirkaMinLabel = new javax.swing.JLabel();
        peptonizacniMinLabel = new javax.swing.JLabel();
        nizsiCukrotvornaMinLabel = new javax.swing.JLabel();
        vyssiCukrotvornaMinLabel = new javax.swing.JLabel();
        odrmutovaciMinLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        toleranceCombo = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();

        jLabel1.setText("Vystírka");

        vystirkaSlider.setMaximum(120);
        vystirkaSlider.setPaintLabels(true);
        vystirkaSlider.setPaintTicks(true);
        vystirkaSlider.setToolTipText(
            Integer.toString(vystirkaSlider.getValue()));
        vystirkaSlider.setValue(0);
        vystirkaSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                vystirkaSliderStateChanged(evt);
            }
        });

        vystiraciCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "37", "38", "39", "40", "41", "42", "43", "44", "45" }));

        jLabel2.setText("Peptonizační teplota");

        peptonizacniCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "51", "52", "53" }));

        jLabel3.setText("Nižší cukrotvorná teplota");

        nizsiCukrCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "62", "63", "64", "65" }));

        jLabel4.setText("Vyšší cukrotvorná teplota");

        vyssiCukrCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "72", "73", "74", "75" }));

        jLabel5.setText("Odrmutovací teplota");

        odrmutovaciCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "75", "76", "77", "78" }));

        peptonizacniSlider.setMaximum(120);
        peptonizacniSlider.setPaintLabels(true);
        peptonizacniSlider.setPaintTicks(true);
        peptonizacniSlider.setToolTipText(
            Integer.toString(vystirkaSlider.getValue()));
        peptonizacniSlider.setValue(0);
        peptonizacniSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                peptonizacniSliderStateChanged(evt);
            }
        });

        vyssiCukrotvornaSlider.setMaximum(120);
        vyssiCukrotvornaSlider.setPaintLabels(true);
        vyssiCukrotvornaSlider.setPaintTicks(true);
        vyssiCukrotvornaSlider.setToolTipText(
            Integer.toString(vystirkaSlider.getValue()));
        vyssiCukrotvornaSlider.setValue(0);
        vyssiCukrotvornaSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                vyssiCukrotvornaSliderStateChanged(evt);
            }
        });

        odrmutovaciSlider.setMaximum(120);
        odrmutovaciSlider.setPaintLabels(true);
        odrmutovaciSlider.setPaintTicks(true);
        odrmutovaciSlider.setToolTipText(
            Integer.toString(vystirkaSlider.getValue()));
        odrmutovaciSlider.setValue(0);
        odrmutovaciSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                odrmutovaciSliderStateChanged(evt);
            }
        });

        nizsiCukrotvornaSlider.setMaximum(120);
        nizsiCukrotvornaSlider.setPaintLabels(true);
        nizsiCukrotvornaSlider.setPaintTicks(true);
        nizsiCukrotvornaSlider.setToolTipText(
            Integer.toString(vystirkaSlider.getValue()));
        nizsiCukrotvornaSlider.setValue(0);
        nizsiCukrotvornaSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                nizsiCukrotvornaSliderStateChanged(evt);
            }
        });

        vystrirkaMinLabel.setText("0 min");

        peptonizacniMinLabel.setText("0 min");

        nizsiCukrotvornaMinLabel.setText("0 min");

        vyssiCukrotvornaMinLabel.setText("0 min");

        odrmutovaciMinLabel.setText("0 min");

        jButton1.setText("Potvrdit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Tolerance");

        toleranceCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0.5", "1.0", "1.5", "2.0" }));
        toleranceCombo.setSelectedIndex(2);

        jLabel7.setText("°C");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(odrmutovaciCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(0, 196, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(peptonizacniCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                                .addComponent(peptonizacniMinLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(peptonizacniSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(vystiraciCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(vystrirkaMinLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vystirkaSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nizsiCukrCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vyssiCukrCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(vyssiCukrotvornaMinLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(vyssiCukrotvornaSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(odrmutovaciMinLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(odrmutovaciSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nizsiCukrotvornaMinLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nizsiCukrotvornaSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(toleranceCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(vystiraciCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(vystrirkaMinLabel))
                    .addComponent(vystirkaSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(peptonizacniCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(peptonizacniMinLabel))
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3))
                    .addComponent(peptonizacniSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nizsiCukrotvornaMinLabel)
                            .addComponent(nizsiCukrotvornaSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nizsiCukrCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(vyssiCukrCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(vyssiCukrotvornaMinLabel))
                    .addComponent(vyssiCukrotvornaSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(odrmutovaciCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(odrmutovaciMinLabel))
                    .addComponent(odrmutovaciSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(toleranceCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void vystirkaSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_vystirkaSliderStateChanged
        vystrirkaMinLabel.setText(vystirkaSlider.getValue()+" min");
    }//GEN-LAST:event_vystirkaSliderStateChanged

    private void peptonizacniSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_peptonizacniSliderStateChanged
        
        peptonizacniMinLabel.setText(peptonizacniSlider.getValue()+" min");
    }//GEN-LAST:event_peptonizacniSliderStateChanged

    private void vyssiCukrotvornaSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_vyssiCukrotvornaSliderStateChanged
        vyssiCukrotvornaMinLabel.setText(vyssiCukrotvornaSlider.getValue()+" min");
    }//GEN-LAST:event_vyssiCukrotvornaSliderStateChanged

    private void odrmutovaciSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_odrmutovaciSliderStateChanged
        odrmutovaciMinLabel.setText(odrmutovaciSlider.getValue()+" min");
    }//GEN-LAST:event_odrmutovaciSliderStateChanged

    private void nizsiCukrotvornaSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_nizsiCukrotvornaSliderStateChanged
        nizsiCukrotvornaMinLabel.setText(nizsiCukrotvornaSlider.getValue()+" min");
    }//GEN-LAST:event_nizsiCukrotvornaSliderStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        model.setCurrentRecipe(new Recipe(
                Float.parseFloat(toleranceCombo.getModel().getSelectedItem().toString()), 
                Integer.parseInt(vystiraciCombo.getModel().getSelectedItem().toString()), vystirkaSlider.getValue(),
                Integer.parseInt(peptonizacniCombo.getModel().getSelectedItem().toString()), peptonizacniSlider.getValue(),
                Integer.parseInt(nizsiCukrCombo.getModel().getSelectedItem().toString()), nizsiCukrotvornaSlider.getValue(),
                Integer.parseInt(vyssiCukrCombo.getModel().getSelectedItem().toString()), vyssiCukrotvornaSlider.getValue(),
                Integer.parseInt(odrmutovaciCombo.getModel().getSelectedItem().toString()), odrmutovaciSlider.getValue()));
        controller.notifyView();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox nizsiCukrCombo;
    private javax.swing.JLabel nizsiCukrotvornaMinLabel;
    private javax.swing.JSlider nizsiCukrotvornaSlider;
    private javax.swing.JComboBox odrmutovaciCombo;
    private javax.swing.JLabel odrmutovaciMinLabel;
    private javax.swing.JSlider odrmutovaciSlider;
    private javax.swing.JComboBox peptonizacniCombo;
    private javax.swing.JLabel peptonizacniMinLabel;
    private javax.swing.JSlider peptonizacniSlider;
    private javax.swing.JComboBox toleranceCombo;
    private javax.swing.JComboBox vyssiCukrCombo;
    private javax.swing.JLabel vyssiCukrotvornaMinLabel;
    private javax.swing.JSlider vyssiCukrotvornaSlider;
    private javax.swing.JComboBox vystiraciCombo;
    private javax.swing.JSlider vystirkaSlider;
    private javax.swing.JLabel vystrirkaMinLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void notifyView() {
        //throw new UnsupportedOperationException("Not supported yet.");
        //TODO
    }

    @Override
    public void reset() {
        throw new UnsupportedOperationException("Not supported yet.");
    }
}
